CREATE SCHEMA IF NOT EXISTS gratitude;
SET search_path TO gratitude;
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, name TEXT NOT NULL, email TEXT UNIQUE NOT NULL, password TEXT NOT NULL, demo BIGINT DEFAULT 0, last_login TEXT NOT NULL DEFAULT '1970-01-01T00:00:00.000Z', email_verified BIGINT NOT NULL DEFAULT 0, onboarding_complete BIGINT NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS auth_sessions (token TEXT PRIMARY KEY, user_id TEXT, expires BIGINT NOT NULL, feed_since TEXT NOT NULL DEFAULT '1970-01-01T00:00:00.000Z', deletion_verified BIGINT NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS circles (id TEXT PRIMARY KEY, name TEXT NOT NULL, kind TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', owner TEXT, invite TEXT UNIQUE NOT NULL, prompt TEXT DEFAULT 'What are you grateful for today?', cadence TEXT DEFAULT 'daily', day TEXT DEFAULT 'Friday', time TEXT DEFAULT '21:00', timezone TEXT DEFAULT 'Europe/London', count BIGINT DEFAULT 3);
CREATE TABLE IF NOT EXISTS members (circle_id TEXT, user_id TEXT, role TEXT NOT NULL DEFAULT 'member', muted BIGINT DEFAULT 0, PRIMARY KEY (circle_id,user_id));
CREATE TABLE IF NOT EXISTS sessions (id TEXT PRIMARY KEY, circle_id TEXT, host TEXT, prompt TEXT NOT NULL, created TEXT NOT NULL, ended TEXT, reflection TEXT DEFAULT '');
CREATE TABLE IF NOT EXISTS posts (id TEXT PRIMARY KEY, circle_id TEXT, author TEXT, body TEXT NOT NULL, image TEXT, created TEXT NOT NULL, visibility TEXT NOT NULL DEFAULT 'circle', session_id TEXT, audio TEXT, background TEXT NOT NULL DEFAULT 'linen', recipient TEXT);
CREATE TABLE IF NOT EXISTS reactions (post_id TEXT, user_id TEXT, kind TEXT NOT NULL, PRIMARY KEY(post_id,user_id,kind));
CREATE TABLE IF NOT EXISTS comments (id TEXT PRIMARY KEY, post_id TEXT, author TEXT, body TEXT NOT NULL, created TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS uploads (id TEXT PRIMARY KEY, owner TEXT, mime TEXT NOT NULL, data BYTEA NOT NULL, generated BIGINT NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS reports (id TEXT PRIMARY KEY, post_id TEXT, reporter TEXT, reason TEXT NOT NULL, created TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS blocks (user_id TEXT, blocked_id TEXT, PRIMARY KEY(user_id,blocked_id));
CREATE TABLE IF NOT EXISTS oauth_identities (provider TEXT NOT NULL, subject TEXT NOT NULL, user_id TEXT NOT NULL, PRIMARY KEY(provider,subject), UNIQUE(user_id,provider));
CREATE TABLE IF NOT EXISTS oauth_attempts (state_hash TEXT PRIMARY KEY, browser_hash TEXT NOT NULL, provider TEXT NOT NULL, verifier TEXT NOT NULL, nonce TEXT NOT NULL, return_path TEXT NOT NULL, link_user TEXT, expires BIGINT NOT NULL, intent TEXT NOT NULL DEFAULT 'login');
CREATE TABLE IF NOT EXISTS oauth_receipts (receipt_hash TEXT PRIMARY KEY, state_hash TEXT NOT NULL, browser_hash TEXT NOT NULL, payload TEXT NOT NULL, expires BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS image_generations (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, created BIGINT NOT NULL, status TEXT NOT NULL, upload_id TEXT);
CREATE TABLE IF NOT EXISTS post_circles (post_id TEXT, circle_id TEXT, PRIMARY KEY(post_id,circle_id));
CREATE TABLE IF NOT EXISTS circle_invitations (id TEXT PRIMARY KEY, circle_id TEXT NOT NULL, sender TEXT NOT NULL, recipient TEXT NOT NULL, created TEXT NOT NULL, UNIQUE(circle_id,recipient));
CREATE TABLE IF NOT EXISTS departure_feedback(id TEXT PRIMARY KEY,reason TEXT NOT NULL,comment TEXT NOT NULL,expires BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS email_tokens (hash TEXT PRIMARY KEY, user_id TEXT NOT NULL, purpose TEXT NOT NULL, expires BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS email_limits (key TEXT PRIMARY KEY, count BIGINT NOT NULL, expires BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS push_subscriptions (endpoint TEXT PRIMARY KEY, user_id TEXT NOT NULL, subscription TEXT NOT NULL, timezone TEXT NOT NULL, last_day TEXT, lease BIGINT NOT NULL DEFAULT 0);
ALTER TABLE auth_sessions ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE circles ADD FOREIGN KEY (owner) REFERENCES users(id);
ALTER TABLE members ADD FOREIGN KEY (circle_id) REFERENCES circles(id) ON DELETE CASCADE;
ALTER TABLE members ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE sessions ADD FOREIGN KEY (circle_id) REFERENCES circles(id) ON DELETE CASCADE;
ALTER TABLE sessions ADD FOREIGN KEY (host) REFERENCES users(id);
ALTER TABLE posts ADD FOREIGN KEY (circle_id) REFERENCES circles(id) ON DELETE CASCADE;
ALTER TABLE posts ADD FOREIGN KEY (author) REFERENCES users(id);
ALTER TABLE posts ADD FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE SET NULL;
ALTER TABLE posts ADD FOREIGN KEY (recipient) REFERENCES users(id);
ALTER TABLE reactions ADD FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE;
ALTER TABLE reactions ADD FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE comments ADD FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE;
ALTER TABLE comments ADD FOREIGN KEY (author) REFERENCES users(id);
ALTER TABLE uploads ADD FOREIGN KEY (owner) REFERENCES users(id);
ALTER TABLE reports ADD FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE;
ALTER TABLE reports ADD FOREIGN KEY (reporter) REFERENCES users(id);
ALTER TABLE blocks ADD FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE blocks ADD FOREIGN KEY (blocked_id) REFERENCES users(id);
ALTER TABLE oauth_identities ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE oauth_attempts ADD FOREIGN KEY (link_user) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE oauth_receipts ADD FOREIGN KEY (state_hash) REFERENCES oauth_attempts(state_hash) ON DELETE CASCADE;
ALTER TABLE image_generations ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE image_generations ADD FOREIGN KEY (upload_id) REFERENCES uploads(id);
ALTER TABLE post_circles ADD FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE;
ALTER TABLE post_circles ADD FOREIGN KEY (circle_id) REFERENCES circles(id) ON DELETE CASCADE;
ALTER TABLE circle_invitations ADD FOREIGN KEY (circle_id) REFERENCES circles(id) ON DELETE CASCADE;
ALTER TABLE circle_invitations ADD FOREIGN KEY (sender) REFERENCES users(id);
ALTER TABLE circle_invitations ADD FOREIGN KEY (recipient) REFERENCES users(id);
ALTER TABLE email_tokens ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE push_subscriptions ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON users FROM PUBLIC, anon, authenticated;
ALTER TABLE auth_sessions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON auth_sessions FROM PUBLIC, anon, authenticated;
ALTER TABLE circles ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON circles FROM PUBLIC, anon, authenticated;
ALTER TABLE members ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON members FROM PUBLIC, anon, authenticated;
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON sessions FROM PUBLIC, anon, authenticated;
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON posts FROM PUBLIC, anon, authenticated;
ALTER TABLE reactions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON reactions FROM PUBLIC, anon, authenticated;
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON comments FROM PUBLIC, anon, authenticated;
ALTER TABLE uploads ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON uploads FROM PUBLIC, anon, authenticated;
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON reports FROM PUBLIC, anon, authenticated;
ALTER TABLE blocks ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON blocks FROM PUBLIC, anon, authenticated;
ALTER TABLE oauth_identities ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON oauth_identities FROM PUBLIC, anon, authenticated;
ALTER TABLE oauth_attempts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON oauth_attempts FROM PUBLIC, anon, authenticated;
ALTER TABLE oauth_receipts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON oauth_receipts FROM PUBLIC, anon, authenticated;
ALTER TABLE image_generations ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON image_generations FROM PUBLIC, anon, authenticated;
ALTER TABLE post_circles ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON post_circles FROM PUBLIC, anon, authenticated;
ALTER TABLE circle_invitations ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON circle_invitations FROM PUBLIC, anon, authenticated;
ALTER TABLE departure_feedback ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON departure_feedback FROM PUBLIC, anon, authenticated;
ALTER TABLE email_tokens ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON email_tokens FROM PUBLIC, anon, authenticated;
ALTER TABLE email_limits ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON email_limits FROM PUBLIC, anon, authenticated;
ALTER TABLE push_subscriptions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON push_subscriptions FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SCHEMA gratitude FROM PUBLIC, anon, authenticated;
CREATE INDEX IF NOT EXISTS posts_created_idx ON posts(created DESC);
CREATE INDEX IF NOT EXISTS posts_author_idx ON posts(author);
CREATE INDEX IF NOT EXISTS members_user_idx ON members(user_id);
CREATE INDEX IF NOT EXISTS post_circles_circle_idx ON post_circles(circle_id);
CREATE INDEX IF NOT EXISTS auth_sessions_user_idx ON auth_sessions(user_id);
CREATE OR REPLACE FUNCTION gratitude.track_login() RETURNS trigger LANGUAGE plpgsql SET search_path = gratitude AS $$
BEGIN
  SELECT last_login INTO NEW.feed_since FROM users WHERE id=NEW.user_id FOR UPDATE;
  UPDATE users SET last_login=to_char(clock_timestamp() AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') WHERE id=NEW.user_id;
  RETURN NEW;
END $$;
CREATE TRIGGER track_gratitude_login BEFORE INSERT ON auth_sessions FOR EACH ROW EXECUTE FUNCTION gratitude.track_login();
